Repository uwblueprint/childrens-aid-society, pull requests merged in 2022-06, with the labels that each got.

#9 Created dummy visits route
  backend/python/app/resources/visit_dto.py
  backend/python/app/rest/__init__.py
  backend/python/app/rest/visit_routes.py
  backend/python/app/services/implementations/visit_service.py
  backend/python/app/services/interfaces/visit_service.py
  backend/python/tests/functional/test_visit_routes.py
  db-init/create-multiple-dbs.sh
Labels: ship 🚢

#13 Set up dummy homepage, /intake, /visit routes
  frontend/src/App.tsx
  frontend/src/components/pages/HomePage.tsx
  frontend/src/components/pages/IntakePage.tsx
  frontend/src/components/pages/VisitPage.tsx
  frontend/src/constants/Routes.ts
Labels: frontend

#11 Added dummy intake route (Julianne + Juthika)
  backend/python/app/resources/intake_dto.py
  backend/python/app/rest/__init__.py
  backend/python/app/rest/intake_routes.py
  backend/python/app/services/implementations/intake_service.py
  backend/python/app/services/interfaces/intake_service.py
  backend/python/tests/functional/test_intake_routes.py
Labels: ship 🚢, backend

#10 Create addresses model
  backend/python/app/models/__init__.py
  backend/python/app/models/address.py
  backend/python/migrations/versions/8a03057d5a04_create_address_model.py
Labels: ship 🚢, db

#18 Created dummy children route
  backend/python/app/resources/child_dto.py
  backend/python/app/rest/__init__.py
  backend/python/app/rest/child_routes.py
  backend/python/app/services/implementations/child_service.py
  backend/python/app/services/interfaces/child_service.py
  backend/python/tests/functional/test_child_routes.py
Labels: ship 🚢, backend

#21 Add new transportation methods
  README.md
  backend/python/app/resources/transportation_method_dto.py
  backend/python/app/resources/user_dto.py
  backend/python/app/services/implementations/intake_service.py
  backend/python/app/services/interfaces/intake_service.py
  backend/python/tests/functional/test_intake_service.py
Labels: backend

#17 Setup CodeQL Analysis
  .github/workflows/codeql-analysis.yml
  .github/workflows/codeql-config.yml
Labels: dev/ci

#20 Create new access_types model
  backend/python/app/models/__init__.py
  backend/python/app/models/access_type.py
  backend/python/migrations/versions/7036da15285b_create_access_types_model.py
Labels: ship 🚢, db

#19 created branches model & updated user model
  backend/python/app/models/__init__.py
  backend/python/app/models/branch.py
  backend/python/app/models/user.py
  backend/python/migrations/versions/6cd80740889b_reference_user_branch_using_lookup_table.py
Labels: ship 🚢, db

#26 Capitalize transport methods
  backend/python/app/models/__init__.py
  backend/python/app/models/transportation_method.py
  backend/python/migrations/versions/5c95f4efed2d_create_transportation_method_model.py
Labels: db

#22 Move codeql config file out of workflows
  .github/configs/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: dev/ci

#27 Created familial and child concerns model
  backend/python/app/models/__init__.py
  backend/python/app/models/child_concern.py
  backend/python/app/models/familial_concern.py
  backend/python/migrations/versions/8ad687618714_create_familial_and_child_concerns_model.py
Labels: ship 🚢, db

#24 Create Caregivers Model
  backend/python/app/models/__init__.py
  backend/python/app/models/caregiver.py
  backend/python/migrations/versions/1f9c523fe04c_create_caregivers_model.py
Labels: changes requested 🔃, db

#23 Created daytime_contacts model
  backend/python/app/models/__init__.py
  backend/python/app/models/daytime_contact.py
  backend/python/migrations/versions/4dfecb9b3a37_daytime_contacts.py
Labels: db

#29 add new branches
  backend/python/app/resources/branch_dto.py
  backend/python/app/services/implementations/branch_service.py
  backend/python/app/services/interfaces/branch_service.py
  backend/python/tests/unit/test_branch_service.py
Labels: changes requested 🔃, backend

#30 Fix import in transport method service
  backend/python/app/services/implementations/transport_method_service.py
  backend/python/tests/functional/test_transport_method_service.py
Labels: backend

#28 Created services to allow creation of new address
  backend/python/app/resources/address_dto.py
  backend/python/app/services/implementations/address_service.py
  backend/python/app/services/interfaces/address_service.py
  backend/python/tests/functional/test_address_service.py
Labels: ship 🚢, backend

#34 Add date to migration file name
  backend/python/migrations/alembic.ini
Labels: db

#35 Enable heroku deployments
  .github/workflows/heroku-deploy-dev-py.yml
Labels: dev/ci

#33 Add New Access Type Service
  backend/python/app/resources/access_type_dto.py
  backend/python/app/services/implementations/access_type_service.py
  backend/python/app/services/interfaces/access_type_service.py
  backend/python/tests/unit/test_access_type_service.py
Labels: ship 🚢, backend

#32 Set up Chakra UI
  frontend/Dockerfile
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/auth/Login.tsx
  frontend/src/components/auth/Signup.tsx
  frontend/src/components/pages/HomePage.tsx
  frontend/src/components/pages/IntakePage.tsx
  frontend/src/components/pages/NotFound.tsx
  frontend/src/components/pages/VisitPage.tsx
  frontend/src/theme/colors.tsx
  frontend/src/theme/index.tsx
  frontend/src/theme/textStyles.tsx
  frontend/yarn.lock
Labels: frontend
